# Generated by Django 5.2.8 on 2025-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_news',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
