# Generated by Django 5.2.8 on 2025-12-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_dislikes_post_likes_postrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=6000),
        ),
    ]
